# Generated by Django 4.0.5 on 2022-07-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_kategoria_produkty_kategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoria',
            name='opis',
        ),
    ]
